name: Integration

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@master
        
      - name: "Setup Node.js"
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
          
      - name: npm run
        run: npm run api-tests
